# Generated by Django 2.2 on 2019-11-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
