# Generated by Django 2.2 on 2019-09-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('time', models.TimeField()),
                ('name', models.CharField(max_length=100)),
                ('people', models.IntegerField()),
                ('info', models.TextField()),
                ('tel', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('initials', models.CharField(max_length=20)),
                ('assign', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('arrived', models.BooleanField(default=False)),
                ('cleared', models.BooleanField(default=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical booking',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booking', models.BooleanField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('people', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='bookings.TableGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='peopletable',
            name='people',
        ),
        migrations.RemoveField(
            model_name='table',
            name='booking',
        ),
        migrations.AddField(
            model_name='alert',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='assign',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tel',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='PeopleTable',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='table',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bookings.TableItem'),
        ),
        migrations.AddField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='bookings.TableItem'),
        ),
    ]
