# Generated by Django 2.2 on 2019-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20190922_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegroup',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
