# Generated by Django 2.2 on 2019-11-28 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField()),
                ('monday', models.CharField(max_length=100)),
                ('tuesday', models.CharField(max_length=100)),
                ('wednesday', models.CharField(max_length=100)),
                ('thursday', models.CharField(max_length=100)),
                ('friday', models.CharField(max_length=100)),
                ('saturday', models.CharField(max_length=100)),
                ('sunday', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
