# Generated by Django 2.2 on 2019-11-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_settings_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
