# Generated by Django 2.2 on 2019-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_tablegroup_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableitem',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
