# Generated by Django 2.2 on 2019-06-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190619_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
