# Generated by Django 2.2 on 2019-11-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_historicalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
