# Generated by Django 2.2 on 2019-07-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_tablegroup_tableitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablegroup',
            name='colour',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
