# Generated by Django 2.2 on 2019-07-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_tablegroup_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='bookings.TableGroup'),
        ),
    ]
