# Generated by Django 2.2 on 2019-07-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20190729_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableitem',
            name='people',
            field=models.IntegerField(default=0),
        ),
    ]
