# Generated by Django 2.2 on 2019-11-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_at_hour',
            field=models.IntegerField(default='50'),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_at_time',
            field=models.IntegerField(default='15'),
        ),
    ]
