# Generated by Django 2.2 on 2019-09-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_tableitem_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
