# Generated by Django 2.2 on 2019-11-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20191128_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='walk_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='walk_in',
            field=models.BooleanField(default=False),
        ),
    ]
