# Generated by Django 2.2 on 2020-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20191129_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('people', models.IntegerField()),
                ('info', models.TextField()),
                ('tel', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
