# Generated by Django 2.2 on 2020-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_takeaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeaway',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
