# Generated by Django 2.2 on 2020-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_takeaway_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('M', 'Meal'), ('D', 'Drinks')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('M', 'Meal'), ('D', 'Drinks')], max_length=1, null=True),
        ),
    ]
