# Generated by Django 2.2 on 2020-10-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20201027_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('M', 'Meal'), ('D', 'Drinks'), ('HT', 'High Tea'), ('AT', 'Afternoon Tea')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('M', 'Meal'), ('D', 'Drinks'), ('HT', 'High Tea'), ('AT', 'Afternoon Tea')], max_length=2, null=True),
        ),
    ]
